### ISSUE TITLE
If this code could color the bond according to different bond length?

### ISSUE THREAD

**Issue by WangLulu97** [radi0sus/xyz2tab#2]
Hi,

Thanks for your code! 

After calculating the bond length, if this code could add the function of "color the bond according to different bond lengths"?  And the range of the color bar also could be tuned.

Thank you!!!

Best regards,
Lulu

**Comment by radi0sus** [comment]
One would take `sel_dist2['distance_calc']`(calculated distances) and map these values to colors using the `matplotlib.colors` module. I think this is a rather special feature and beyond the scope of this script. Maybe I'll add this in the future but I think it would be better writing a separate script for this.
