### ISSUE TITLE
Does not print all information as in the examples

### ISSUE THREAD

**Issue by derwisz** [radi0sus/xyz2tab#4]
python3 xyz2tab.py h2o.com
Traceback (most recent call last):
  File "xyz2tab.py", line 19, in <module>
    sys.stdout.reconfigure(encoding='utf-8')
AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'

After commenting line 19 I get:

python3 xyz2tab.py h2o.com

-------------------  -----------
Filename          :  h2o.com
Number of atoms   :  3
Sum formula       :  H₂O
Formula weight    :  18.02 g/mol
Excluded atoms    :  None
Excluded elements :  None
Included contacts :  None
Covalent radius + :  8.00 %
-------------------  -----------

| Element   |   Atom count |   Mass fraction /% |   Cov. radius /Å |   Cov. radius + /Å |
|-----------|--------------|--------------------|------------------|--------------------|
| H         |            2 |              11.19 |             0.31 |               0.33 |
| O         |            1 |              88.81 |             0.66 |               0.71 |
Traceback (most recent call last):
  File "xyz2tab.py", line 442, in <module>
    dist_df['cov_radius2'])+(dist_df['cov_radius1'] +
  File "/Users/derwiszck/anaconda3/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 1048, in wrapper
    result = na_op(lvalues, rvalues)
  File "/Users/derwiszck/anaconda3/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 965, in na_op
    import pandas.core.computation.expressions as expressions
  File "/Users/derwiszck/anaconda3/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 19, in <module>
    from pandas.core.computation.check import _NUMEXPR_INSTALLED
  File "/Users/derwiszck/anaconda3/lib/python3.6/site-packages/pandas/core/computation/check.py", line 3, in <module>
    ne = import_optional_dependency("numexpr", raise_on_missing=False, on_version="warn")
  File "/Users/derwiszck/anaconda3/lib/python3.6/site-packages/pandas/compat/_optional.py", line 90, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/derwiszck/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/derwiszck/anaconda3/lib/python3.6/site-packages/numexpr/__init__.py", line 48, in <module>
    nthreads = _init_num_threads()
  File "/Users/derwiszck/anaconda3/lib/python3.6/site-packages/numexpr/utils.py", line 137, in _init_num_threads
    requested_threads = int(os.environ['OMP_NUM_THREADS'])
ValueError: invalid literal for int() with base 10: '2,1'

Please let me know if there is a need of any information.
Cheers, 
---
derwiszck

**Comment by radi0sus** [comment]
The `AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'` could be from an older Python version. I think if you upgrade to a more recent Python version there will be no error message. However, this is only important for Windows, so you can leave that line commented (in case you're using Linux or MacOS).

Regarding your second problem. I don't know how the atom coordinates are arranged in `h2o.com` (Is this an input file for a program?). The script accepts only standard xyz files. Please check [https://en.wikipedia.org/wiki/XYZ_file_format](https://en.wikipedia.org/wiki/XYZ_file_format) and if the atom coordinates are arranged in a similar way in `h2o.com`. You can also post your file her, so that I can check it.

**Comment by derwisz** [comment]
Hey, thanks.
I tried python2.7, python3, python3.10, python3.11, python3.6 and python3.9  versions and I always get the same errors. 
Commenting the line above is the only way to avoid the direct error at macOS Ventura. Then the second error appears.
Sorry for the extension. It is in standard xyz format for the testing only:
cat h2o.xyz
3
0 1
 O                  2.00277523    1.06845512    0.00000000
 H                  2.96277523    1.06845512    0.00000000
 H                  1.68232065    1.97339095    0.00000000

Could be the problem anaconda?
python -V
Python 3.6.9 :: Anaconda, Inc.

**Comment by radi0sus** [comment]
The coordinates are fine. Tried them with the script on Ventura as well. But I don't use the Anaconda package to run Python programs. I'm also not very familiar with the Anaconda environment. What happens if you remove the line breaks starting from line 443 (or 442):
`dist_df['distance_radii'] = (dist_df['cov_radius1'] + dist_df['cov_radius2'])+(dist_df['cov_radius1'] + dist_df['cov_radius2'])*radii_ext`

**Comment by radi0sus** [comment]
I got the following output from your coordinates after executing the script:

`python3 xyz2tab.py h2o.xyz`

-------------------  -----------
Filename          :  h2o.xyz
Number of atoms   :  3
Sum formula       :  H₂O
Formula weight    :  18.02 g/mol
Excluded atoms    :  None
Excluded elements :  None
Included contacts :  None
Covalent radius + :  8.00 %
-------------------  -----------

| Element   |   Atom count |   Mass fraction /% |   Cov. radius /Å |   Cov. radius + /Å |
|-----------|--------------|--------------------|------------------|--------------------|
| H         |            2 |              11.19 |             0.31 |               0.33 |
| O         |            1 |              88.81 |             0.66 |               0.71 |

| Atoms   |   Bond length /Å |
|---------|------------------|
| O0–H1   |           0.9600 |
| O0–H2   |           0.9600 |

| Atoms   | Bond lengths /Å   |
|---------|-------------------|
| O–H     | 0.9600 / 0.9600   |

| Atoms   |   Count |   Mean /Å |   Median /Å |   Sam. std. dev. |   Pop. std. dev. |   Std. error |   Skewness |
|---------|---------|-----------|-------------|------------------|------------------|--------------|------------|
| O–H     |       2 |      0.96 |        0.96 |                0 |                0 |            0 |        nan |

| Atoms    |   Angle /° |
|----------|------------|
| H1–O0–H2 |     109.50 |

| Atoms   |   Angle /° |
|---------|------------|
| H–O–H   |     109.50 |

| Atoms   |   Count |   Mean /° |   Median /° |   Sam. std. dev. |   Pop. std. dev. |   Std. error |   Skewness |
|---------|---------|-----------|-------------|------------------|------------------|--------------|------------|
| H–O–H   |       1 |     109.5 |       109.5 |              nan |                0 |          nan |        nan |
