### ISSUE TITLE
NumPy ValueError

### ISSUE THREAD

**Issue by LuckyVNN** [radi0sus/xyz2tab#5]
![image](https://github.com/radi0sus/xyz2tab/assets/118751153/ebac14d2-f276-4f05-a16c-2e004821784e)

Hello, I'm trying to use your code but i cannot solve this problem, can you check it out ?
tysm

**Comment by radi0sus** [comment]
Do you get this error message for all xyz files or only for specific files? Please try py.txt (pyridine xyz example from Wikipedia) and report back.

[py.txt](https://github.com/radi0sus/xyz2tab/files/12495720/py.txt)
